name: Android Check
on:
  pull_request:
    paths-ignore:
    - .github/workflows/linux*
    - .github/workflows/ios*
    - '**/*_tests/**'
    - CONTRIBUTORS
    - LICENSE
    - NOTICE
    - README.md
    - docs/**
    - generator/**
    - iphone/**
    - packaging/**
    - pyhelpers/**
    - qt*/**
    - skin_generator/**
    - track_generator/**
    - xcode/**

jobs:
  android-check:
    name: Build Android Debug
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Parallel submodules checkout
        shell: bash
        run: |
          git submodule update --init --recursive --jobs=10

      - name: Cache ccache artifacts
        uses: actions/cache@v2
        with:
          path: ~/.ccache
          key: ccache

      - name: Configure in Open Source mode
        shell: bash
        run: |
          export CC="$(which ccache) $(which gcc)"
          export CXX="$(which ccache) $(which g++)"
          ./configure.sh

      - name: Set up SDK
        shell: bash
        run: |
          (cd tools/android; ./set_up_android.py --sdk $ANDROID_SDK_ROOT)

      - name: Free Space
        shell: bash
        run: df -h

      - name: Compile
        shell: bash
        working-directory: android
        run: |
          export PATH="$(dirname $ANDROID_SDK_ROOT/cmake/*/bin/.|tail -n1):$PATH" # Use CMake from SDK
          echo $PATH
          cmake --version
          ninja --version
          ./gradlew -Parm64 assembleWebDebug

      - name: Upload arm64-v8a debug apk
        uses: actions/upload-artifact@v2
        with:
          name: android-web-arm64-v8a-debug
          path: android/build/outputs/apk/android-web-debug-*.apk
          if-no-files-found: error
