name: Check
on:
  pull_request:

jobs:
  desktop-check:
    name: Desktop Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Parallel submodules checkout
        shell: bash
        run: |
          git submodule update --init --recursive --jobs=10

      - name: Checkout world_feed_integration_tests_data
        uses: actions/checkout@v2
        with:
          repository: omapsapp/world_feed_integration_tests_data
          path: data/world_feed_integration_tests_data

      - name: Configure
        shell: bash
        run: |
          ./configure.sh

      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get update && sudo apt-get install -y \
              cmake \
              ninja-build \
              clang \
              ccache \
              python \
              qtbase5-dev \
              libqt5svg5-dev \
              libc++-dev \
              libboost-iostreams-dev \
              libglu1-mesa-dev \
              libsqlite3-dev \
              zlib1g-dev

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: ~/.ccache
          key: desktop-cache

      - name: Configure
        shell: bash
        run: |
          ccache -M 4G
          export CC="ccache clang"
          export CXX="ccache clang++"
          cmake . -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug

      - name: Compile
        shell: bash
        run: cmake --build build --target all

      - name: Test
        shell: bash
        working-directory: build
        # generator_integration_tests - https://github.com/omapsapp/omapsapp/issues/225
        # partners_api_tests - https://github.com/omapsapp/omapsapp/issues/218
        # routing_integration_tests - https://github.com/omapsapp/omapsapp/issues/221
        # routing_quality_tests - https://github.com/omapsapp/omapsapp/issues/215
        # drape_tests - requires X Window
        run: |
          ../tools/python/run_desktop_tests.py \
            -o /dev/stdout \
            -f $PWD \
            -u ../data/ \
            -d ../data/ \
            -e generator_integration_tests \
            -e partners_api_tests \
            -e routing_integration_tests \
            -e routing_quality_tests \
            -e drape_tests
